### ISSUE TITLE
Help to install : postgres db will be create on localhost

### ISSUE THREAD

**Issue by tomamplius** [domovikapp/domovik-server#1]
Hi,

Sorry, i need help because i can't install domoviapp databases

`domovick.env` file is
~~~
DATABASE_URL=ecto://domovik:secret@postgres.net.lgy.fr/domovik
SECRET_KEY=secret
PORT=4000
MIX_ENV=prod
~~~

i install with the bellow command

~~~
source domovik.env 
mix setup
~~~

and i get error fail to connect "localhost:5432"

~~~
22:59:38.313 [error] GenServer #PID<0.543.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

22:59:38.328 [error] GenServer #PID<0.547.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Domovik.Repo couldn't be created: killed
~~~
Thanks for your help

**Comment by tomamplius** [comment]
Fix with set -a 
~~~
set -a
source domovik.env 
mix setup
~~~

But there is an issue in the readme.

~~~
DATABASE_URL=ecto://domovik:secret@postgres.net.lgy.fr/domovik
SECRET_KEY_BASE=secret
PORT=4000
MIX_ENV=prod
~~~

The variable is not SECRET_KEY but SECRET_KEY_BASE

**Comment by tomamplius** [comment]
#2 to fix the last point
